version: "3"

services:
  inf3995-frontend:
    build: ./frontend
    image: inf3995-frontend
    volumes:
      - ./frontend:/root/frontend
      - /root/frontend/node_modules
    ports:
      - 3000:3000
  inf3995-backend:
    build: ./backend
    image: inf3995-backend
    volumes:
      - ./backend:/root/backend
    ports:
      - 5000:5000
    devices:
      - "/dev/bus:/dev/bus"
  inf3995-simulation:
    build: ./simulation
    image: inf3995-simulation
    volumes:
      - ./simulation:/root/simulation
    container_name: inf3995-simulation
  inf3995-crazyflie-firmware:
    build: ./crazyflie-firmware
    image: inf3995-firmware
    volumes:
      - ./crazyflie-firmware:/root/crazyflie-firmware
