version: "3"

services:
  inf3995-frontend:
    build: ./frontend
    image: inf3995-frontend
    volumes:
      - ./frontend:/root/frontend
      - /root/frontend/node_modules # ignore node_modules
    ports:
      - 3000:3000
    stdin_open: true

  inf3995-backend:
    build: ./backend
    image: inf3995-backend
    volumes:
      - ./backend:/root/backend
    ports:
      - 5000:5000
      - 80:80
      - 81:81
      - 82:82
      - 83:83

    devices:
      - "/dev/bus:/dev/bus"

  inf3995-simulation:
    build: ./simulation
    image: inf3995-simulation
    volumes:
      - ./simulation:/root/simulation
    container_name: inf3995-simulation

  inf3995-crazyflie-firmware:
    build: ./crazyflie-firmware
    image: inf3995-crazyflie-firmware
    volumes:
      - ./crazyflie-firmware:/root/crazyflie-firmware
    ports:
      - 9000:9000
    devices:
      - /dev/bus:/dev/bus
